name: Linux Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        BuildType: [Debug, Release]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: lukka/get-cmake@latest

      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure
        run: >-
          cmake -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP/build" -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.BuildType }} -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build "$RUNNER_TEMP/build" --parallel --config ${{ matrix.BuildType }}

      - name: Run unit tests
        run: >-
          ctest --test-dir "$RUNNER_TEMP/build" --build-config ${{ matrix.BuildType }}
          --output-on-failure --no-tests=error
